### ISSUE TITLE
Authenticity proof in Gardener

### ISSUE THREAD

**Issue by marcozecchini** [EspeoBlockchain/gardener-smart-contracts#13]
Hi all,
I just start reading about this project and I would like to have some deeper information.

I briefly read the documentation. A central focus of Oraclize is related to providing an authenticity proof of the external data, ensuring its authenticity. I was wondering how this is achieved in your solution? Is Gardener just an off-chain trusted server or it provides also more information regarding the authenticity of data?

Thank you,
Marco.

**Comment by kwedrowicz** [comment]
Hi @marcozecchini! We are currently far in progress of delivering proofs to user requests. For now we are focusing on proving data selection using [Intel SGX](https://github.com/EspeoBlockchain/gardener-server/issues/21) (we use this technique also to get truly random numbers). More on this @kss-espeo can explain to you. Later we want also to prove that data on which we operate is really fetched from a given data source. Proper technique isn't selected yet.

**Comment by kwedrowicz** [comment]
@kss-espeo will provide more details and ETA to you.

**Comment by kss-espeo** [comment]
Hi @marcozecchini and thanks for reaching out!

Indeed, we are currently working on integrating Intel SGX as our first mechanism that will provide authenticity proofs. The idea is that whoever hosts Gardener does _not_ have to be a Third Trusted Party even though currently this is the case. After we implement Intel SGX, critical oracle work is going to be done within Intel SGX enclaves and this will be provable using Intel Attestation Service. That way, the only Third Trusted Party is Intel.

If you'd like to track our progress, this is implemented within https://github.com/EspeoBlockchain/gardener-server/issues/21 and https://github.com/EspeoBlockchain/gardener-server/issues/22 . ETA = 2-3 weeks.
