### ISSUE TITLE
UsingOracle contract is not checking if the request is pending

### ISSUE THREAD

**Issue by tcichowicz** [EspeoBlockchain/gardener-smart-contracts#5]
When requesting data from oracle the requests are marked as pending in `pendingRequests` mapping. However, the `__callback` method does not check if the call is indeed a pending request. I'd suggest adding an `onlyPendingRequest` modifier to check it.

**Comment by starspire** [comment]
Such a check would be redundant because the same is in Oracle contract itself. What we can is to remove this pendingRequests mapping as leave it as it is for the extending contract purposes.

**Comment by tcichowicz** [comment]
Ok, with the `onlyFromOracle` modifier this would be redundant and a bad example so contradictory to the purpose of the `UsingOracle` contract.

There's another catch. Since this mapping is private it's not really usable (aside from the fact that marking requests as completed is missing). Right now it's not mandatory to have contracts inherit from `UsingOracle` so in my view this contract serves its role mostly as an example. How about rewriting it as an `UsingOracleExampleContract` per analogy to the `UsingOraclizeExampleContract`?

**Comment by kss-espeo** [comment]
@starspire is this still relevant?
